server:
  port: 9092
  connection-timeout: 30000s
  servlet:
    context-path: /eurekaClient
spring:
  application:
    name: eureka-client #
eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
  instance:
    hostname: localhost
    instance-id: eurekaClient2
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true