server:
  port: 9090
  connection-timeout: 30000s
  servlet:
    context-path: /eurekaClient
spring:
  application:
    name: eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka1:9000/eureka/
  instance:
    hostname: localhost
    instance-id: eurekaClient1  #实例注册到eureka服务器上的唯一实例ID
    lease-renewal-interval-in-seconds: 30   #过多长时间发送心跳给eureka服务器，表明它仍然活着，默认为30s
    prefer-ip-address: true  #显示IP地址,便于在eureka-server控制台点击client名，通过ip:port直接访问服务