server:
  port: 9002
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: true #高可用的是就要开启注册自己了
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka2:9000/eureka/ #注册到9000 eurekaserver1上

