spring:
  profiles:
    active: jdbc
  application:
    name: config-jdbc-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/enough_test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: lidong123
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    config:
      label: master
      server:
        jdbc: true
server:
  port: 8769
spring.cloud.config.server.jdbc.sql: SELECT `key`, `value` from `config_properties` where `application`=? and `profile`=? and `label`=?

#SpringCloud 1.5版本暴露接口，暴露/bus-refresh接口
#management.security.enabled=false
#SpringCloud 2.0.0版本以后暴露接口方式
#management.endpoints.web.exposure.include=bus-refresh
management:  #actuator
  endpoints:
    web:
      #base-path: / #默认是/actuator 前缀，可以在这里修改
      exposure:
        include: "*"  #打开全部请求端点
        #include: refresh,health,info #打开部分

