server:
  port: 8762
spring:
  application:
    name: eureka-server #应用名称保持一致
eureka:
  client:
    register-with-eureka: true #高可用的是就要开启注册自己了
    fetch-registry: true #同步其他相邻eureka节点数据，默认true
    serviceUrl:
      #defaultZone: http://127.0.0.1:${server.port}/eureka/
      defaultZone: http://eureka1:8761/eureka/ #注册到8761 eurekaServer1上
  instance:
    hostname: eureka2
